version: '3.3'

services:
  app:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_ENV=dev
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - JWT_SECRET=705cd8cdf0a9671a5a78af10ab8679d69386b7e351803757ea86ae29792f2d48
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  jenkins:
    image: jenkins/jenkins:jdk17-preview
    ports:
      - 8081:8080
      - 50000:50000
    networks:
      jenkins_net:
        aliases:
          - jenkins_net

volumes:
  postgres_data:
  jenkins_data:
networks:
  jenkins_net: